// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat_peer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Introduction struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Age                  int64    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Introduction) Reset()         { *m = Introduction{} }
func (m *Introduction) String() string { return proto.CompactTextString(m) }
func (*Introduction) ProtoMessage()    {}
func (*Introduction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *Introduction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Introduction.Unmarshal(m, b)
}
func (m *Introduction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Introduction.Marshal(b, m, deterministic)
}
func (m *Introduction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Introduction.Merge(m, src)
}
func (m *Introduction) XXX_Size() int {
	return xxx_messageInfo_Introduction.Size(m)
}
func (m *Introduction) XXX_DiscardUnknown() {
	xxx_messageInfo_Introduction.DiscardUnknown(m)
}

var xxx_messageInfo_Introduction proto.InternalMessageInfo

func (m *Introduction) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Introduction) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type Msg struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Test                 string   `protobuf:"bytes,2,opt,name=test,proto3" json:"test,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Msg) GetTest() string {
	if m != nil {
		return m.Test
	}
	return ""
}

func init() {
	proto.RegisterType((*Introduction)(nil), "chat.peer.Introduction")
	proto.RegisterType((*Msg)(nil), "chat.peer.Msg")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0xb0, 0x53, 0x53, 0x8b, 0x94, 0x6c, 0xb8,
	0x78, 0x3c, 0xf3, 0x4a, 0x8a, 0xf2, 0x53, 0x4a, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x84, 0xa4, 0xb8,
	0x38, 0xf2, 0x32, 0x93, 0xb3, 0xf3, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0xe0, 0x7c, 0x21, 0x01, 0x2e, 0xe6, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20,
	0x10, 0x53, 0xc9, 0x98, 0x8b, 0xd9, 0xb7, 0x38, 0x5d, 0x48, 0x82, 0x8b, 0x3d, 0x39, 0x3f, 0xaf,
	0x24, 0x35, 0xaf, 0x04, 0xaa, 0x07, 0xc6, 0x15, 0x12, 0xe2, 0x62, 0x29, 0x49, 0x2d, 0x2e, 0x01,
	0xeb, 0xe1, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0x8e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x7b, 0x78, 0xd3, 0x29, 0x92, 0x00, 0x00, 0x00,
}
